/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ASUS
 */
public class Home extends javax.swing.JFrame {

private String FilePath;
private JFrame frame;
    private String filePath;

    public Home() {
        initComponents();
        //disable the maximize button
    setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitcode = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submitcode.setBackground(new java.awt.Color(102, 102, 255));
        submitcode.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        submitcode.setText("Click here to choose your code...");
        submitcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitcodeActionPerformed(evt);
            }
        });
        getContentPane().add(submitcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 380, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Desktop - 1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitcodeActionPerformed

         
        // calling selector file chooser
 JFileChooser jf = new JFileChooser();
FileNameExtensionFilter filter = new FileNameExtensionFilter(
 "JAVA and C++ source files", "java", "cpp");
jf.setAcceptAllFileFilterUsed(false);
jf.setFileFilter(filter);
int returnVal = jf.showOpenDialog(null);
 if(returnVal == JFileChooser.APPROVE_OPTION) {
String filepath=jf.getSelectedFile().getAbsolutePath();
   setFilePath(filepath);
   ComplexityCalculationProc(filepath,jf.getSelectedFile().getName());
   //JOptionPane.showMessageDialog(null, "Complexity Calculation Completed","Success",JOptionPane.INFORMATION_MESSAGE);
}
    }//GEN-LAST:event_submitcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton submitcode;
    // End of variables declaration//GEN-END:variables

    public String getFilePath() {
		return FilePath;
	}
    private void setFilePath(String filepath) {
        FilePath = filePath;
    }

    private void ComplexityCalculationProc(String filepath, String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

//comment
//mkjnbhvgyv
